services:
  app:
    image: golang:1.24-bookworm
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DB_HOST: db
      DB_NAME: testdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
  db:
    container_name: go-migrate-db
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
volumes:
  postgres-data:
